Remove import from bootstrap esm
Azure-Samples/ms-identity-javascript-react-spa pull request #31
Opened 2022-10-12 12:37 UTC by trondal

## Purpose

* Removed wrong import from Bootstrap

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-10-12 12:37 UTC, ghost commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/Azure-Samples/ms-identity-javascript-react-spa?pullRequest=31) <br/>All CLA requirements met.

2022-10-13 21:25 UTC, derisen commented on src/components/SignInButton.jsx
> +import Dropdown from "react-bootstrat/Dropdown";
```suggestion
import Dropdown from "react-bootstrap/Dropdown";
```

2022-10-13 21:26 UTC, derisen requested changes
@trondal thanks for catching this! One comment to address

2022-10-19 17:25 UTC, derisen approved these changes
Thanks @trondal , LGTM. It seems you also need to sign the CLA -see the bot [comment](https://github.com/Azure-Samples/ms-identity-javascript-react-spa/pull/31#issuecomment-1283922947). You should be able to omit the company field if that's not relevant.

2022-10-22 18:42 UTC, trondal commented
@microsoft-github-policy-service agree [company="{default}"]

2022-10-22 18:42 UTC, trondal commented
@microsoft-github-policy-service agree

2022-10-22 20:27 UTC, merged